import assert from 'node:assert/strict';

export async function verifySelection({ page, plan, importPlan, choose, planPoint, move, project, output }) {
  const room = { id: 'base', type: 'room', name: '', x: 0, y: 0, w: 640, h: 420, color: '#ffffff', locked: false, surface: 'plain' };
  const a = { id: 'a', type: 'furniture', kind: 'chabudai', x: 43, y: 73, w: 90, h: 90, rotation: 0, locked: false };
  const b = { ...a, id: 'b', kind: 'zabuton', x: 263, y: 173, w: 55, h: 59, rotation: 25 };
  const locked = { ...a, id: 'locked', kind: 'andon', x: 450, y: 80, w: 32, h: 32, locked: true };
  const wall = { id: 'wall', type: 'wall', x1: 40, y1: 350, x2: 340, y2: 350, locked: false };
  const label = { id: 'label', type: 'text', text: '庭', x: 470, y: 300, size: 24, rotation: 0, locked: false };
  const data = plan([room, a, b, locked, wall, label]);
  const state = () => page.evaluate(() => window.__editorTest.snapshot());
  const ids = () => page.evaluate(() => window.__editorTest.selection());
  const entities = async () => (await state()).floors[0].entities;
  const click = async (x, y, ctrl = false) => {
    const p = await planPoint(x, y);
    if (ctrl) await page.keyboard.down('Control');
    await page.mouse.click(p.x, p.y);
    if (ctrl) await page.keyboard.up('Control');
  };
  await page.locator('[data-view-mode="plan"]').click();
  await importPlan(data);
  await choose('[data-tool="select"]');
  for (const [x, y] of [[88, 118], [290, 200], [466, 96], [180, 350], [470, 300], [600, 380]]) await click(x, y, true);
  assert.equal((await ids()).length, 6);
  await click(290, 200, true);
  assert.equal((await ids()).length, 5);
  await click(290, 200, true);
  assert.equal(await page.locator('.selection-count').textContent(), '6件選択中（固定 1件）');
  const before = await entities();
  await move(await planPoint(88, 118), 70, 35);
  const after = await entities();
  const dx = after[1].x - a.x, dy = after[1].y - a.y;
  assert.ok(dx || dy);
  assert.deepEqual(after[3], locked);
  assert.equal(after[0].x - room.x, dx);
  assert.equal(after[2].x - b.x, dx);
  assert.equal(after[2].y - b.y, dy);
  assert.equal(after[4].x1 - wall.x1, dx);
  assert.equal(after[4].x2 - wall.x2, dx);
  assert.equal(after[5].x - label.x, dx);
  await page.screenshot({ path: `${output}/multi-selection.png` });
  await page.keyboard.press('Control+z');
  assert.deepEqual(await entities(), before);
  await page.keyboard.press('Control+y');
  assert.deepEqual(await entities(), after);
  // 読み込むと値がそろえられる（固定していない物にも locked: false が付くなど）ので、読み込んだあとの形と比べる
  await importPlan(data);
  const imported = await entities();
  await click(88, 118, true);
  await click(290, 200, true);
  await move(await planPoint(88, 118), 60, 40, true);
  assert.deepEqual(await entities(), imported, 'Escape restores the whole group');
  const p = await planPoint(88, 118);
  await page.mouse.move(p.x, p.y);
  await page.mouse.down();
  await page.mouse.move(p.x + 70, p.y + 30, { steps: 5 });
  await page.locator('#planCanvas').dispatchEvent('pointercancel', { pointerId: 1 });
  await page.mouse.up();
  assert.deepEqual(await entities(), imported, 'pointer cancellation never commits');
  await click(466, 96, true);
  await page.keyboard.press('Delete');
  assert.deepEqual((await entities()).map(item => item.id), ['base', 'locked', 'wall', 'label']);
  await page.keyboard.press('Control+z');
  assert.deepEqual(await entities(), imported);
  console.log('PASS: Ctrl selection, mixed-entity group movement, fixed items, cancellation and batch undo/delete');

  await importPlan(data);
  const fresh = await entities();
  await choose('[data-tool="wall"]');
  await click(88, 118);
  assert.deepEqual(await ids(), ['a']);
  assert.equal((await entities()).length, 6, 'quick click selects without drawing a wall');
  await choose('[data-furniture="zabuton"]');
  const held = await planPoint(88, 118);
  await page.mouse.move(held.x, held.y);
  await page.mouse.down();
  await page.waitForTimeout(600);
  assert.deepEqual(await ids(), ['a']);
  await page.mouse.move(held.x + 60, held.y + 30, { steps: 5 });
  await page.mouse.up();
  assert.equal((await entities()).length, 6, 'long press does not place extra furniture');
  assert.notEqual((await entities())[1].x, a.x);
  await page.keyboard.press('Control+z');
  assert.deepEqual(await entities(), fresh);
  await choose('[data-furniture="zabuton"]');
  await move(await planPoint(200, 250), 40, 20);
  assert.equal((await entities()).length, 7);
  await page.keyboard.press('Control+z');
  assert.deepEqual(await entities(), fresh, 'placement plus drag is one undo step');
  await choose('[data-furniture="andon"]');
  await move(await planPoint(200, 250), 40, 20, true);
  assert.equal((await entities()).length, 6, 'cancelled placement leaves no furniture');
  console.log('PASS: click/hold selection, cancelled placement, single-step placement undo');

  await importPlan(plan([room, a, b]));
  const three = await entities();
  await choose('[data-tool="select"]');
  await page.locator('[data-view-mode="three"]').click();
  await page.waitForTimeout(300);
  const pa = await project(88, 118, 0.41), pb = await project(290, 200, 0.16);
  await page.keyboard.down('Control');
  await page.mouse.click(pa.x, pa.y);
  await page.mouse.click(pb.x, pb.y);
  await page.keyboard.up('Control');
  assert.deepEqual((await ids()).sort(), ['a', 'b']);
  await move(pa, 35, 20);
  const moved3d = await entities();
  assert.notEqual(moved3d[1].x + ',' + moved3d[1].y, a.x + ',' + a.y);
  assert.equal(moved3d[2].x - b.x, moved3d[1].x - a.x);
  assert.equal(moved3d[2].y - b.y, moved3d[1].y - a.y);
  await page.keyboard.press('Control+z');
  assert.deepEqual(await entities(), three);
  console.log('PASS: 3D Ctrl selection and group drag');

  // Ctrl+ドラッグで囲んで選び、R で全体を回し、矢印キー・Ctrl+D・Ctrl+C/V・Ctrl+A・Esc を使う
  await page.locator('[data-view-mode="plan"]').click();
  await importPlan(data);
  await choose('[data-tool="select"]');
  const from = await planPoint(20, 50), to = await planPoint(360, 260);
  await page.keyboard.down('Control');
  await page.mouse.move(from.x, from.y);
  await page.mouse.down();
  await page.mouse.move(to.x, to.y, { steps: 6 });
  await page.mouse.up();
  await page.keyboard.up('Control');
  assert.deepEqual((await ids()).sort(), ['a', 'b'], 'Ctrl+drag selects what is inside the box');
  assert.match(await page.locator('#toolHint').textContent(), /2個を選択中/);
  const center = item => ({ x: item.x + item.w / 2, y: item.y + item.h / 2 });
  const pick = async id => (await entities()).find(item => item.id === id);
  const [a0, b0] = [await pick('a'), await pick('b')];
  await page.keyboard.press('r');
  const [a1, b1] = [await pick('a'), await pick('b')];
  assert.deepEqual([a1.rotation, b1.rotation], [90, 115], 'R turns every piece');
  const gap0 = { x: center(b0).x - center(a0).x, y: center(b0).y - center(a0).y };
  const gap1 = { x: center(b1).x - center(a1).x, y: center(b1).y - center(a1).y };
  assert.ok(Math.abs(gap1.x + gap0.y) <= 1.5 && Math.abs(gap1.y - gap0.x) <= 1.5, `the group turns as one: ${JSON.stringify([gap0, gap1])}`);
  await page.keyboard.press('Control+z');
  await page.keyboard.press('ArrowRight');
  assert.deepEqual([(await pick('a')).x, (await pick('b')).x], [a0.x + 20, b0.x + 20], 'arrow keys move the selection');
  await page.keyboard.press('Control+d');
  let all = await entities();
  assert.equal(all.length, 8, 'Ctrl+D duplicates the selection');
  const copies = all.slice(6);
  assert.deepEqual(copies.map(item => item.kind).sort(), ['chabudai', 'zabuton']);
  assert.deepEqual((await ids()).sort(), copies.map(item => item.id).sort(), 'the copies are selected');
  assert.equal(copies.find(item => item.kind === 'chabudai').x, a0.x + 20 + 40);
  await page.keyboard.press('Control+c');
  await page.keyboard.press('Control+v');
  all = await entities();
  assert.equal(all.length, 10, 'Ctrl+V pastes the copied things');
  assert.equal(all.slice(8).find(item => item.kind === 'chabudai').x, a0.x + 20 + 80, 'pasting on the same floor moves the copies a little');
  await page.keyboard.press('Control+a');
  assert.equal((await ids()).length, 10, 'Ctrl+A selects everything on the floor');
  await page.keyboard.press('Escape');
  assert.deepEqual(await ids(), [], 'Escape clears the selection');
  await choose('[data-tool="wall"]');
  assert.match(await page.locator('#toolHint').textContent(), /壁.*ドラッグで壁を描く.*クリックで選ぶ/);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#toolHint').isHidden(), true, 'no hint in the select tool with nothing selected');
  console.log('PASS: Ctrl+drag box selection, turning a group, arrow keys, duplicate, copy and paste, select all and the tool hint');
  await page.locator('[data-view-mode="split"]').click();
  await importPlan(plan());
  await choose('[data-tool="select"]');
}
